server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # serve app
    location / {
        try_files $uri $uri/ /index.html;
    }

    # proxy API calls to the internal docker service 'api'
    location /gaitid/ {
        proxy_pass http://api:5002/gaitid/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    # optional: serve static uploads (if you want to expose /tmp/uploads)
    location /uploads/ {
        alias /tmp/uploads/;
        autoindex off;
    }
}
