# Model parameters
input_shape=90,1



# Evaluation
 
model_save_path=models
best_model_pattern=*best*.pt

local_data_path=sample_test_data
file_name_for_gait=test_data*.csv


learning_rate = 0.0001, 0.00005
batch_size = 16, 32
optimizer = adam, adamw
weight_decay = 0, 1e-3, 1e-5
epochs = 100