# Model parameters
input_shape=180,1

window_size=128
stride=64
batch_size=64

# Evaluation
 
model_save_path=models
best_model_pattern=*best*.pt

local_data_path=sample_test_data
file_name_for_gait=test_data*.csv

MLFLOW_TRACKING_URI=http://127.0.0.1:5001
MLFLOW_EXPERIMENT=wifi-har_id-inference-monitoring 

num_classes = 30
