# Model parameters
input_shape=90,1

window_size=128
stride=64
batch_size=8

# Evaluation
 
model_save_path=models
best_model_pattern=*best*.pt

local_data_path=sample_test_data
file_name_for_gait=test_data*.csv

 